/**
 * SOURCE OF TRUTH KEYWORDS: generatePostgresDdl, SQL_ON_DELETE
 *
 * WHAT:  Emits PostgreSQL `CREATE TABLE` DDL with foreign-key constraints.
 * WHY:   Tables are emitted first and every FK is added afterwards via ALTER
 *        TABLE, so the script runs top-to-bottom regardless of the order the
 *        user drew the entities in — ordering CREATE statements by dependency
 *        breaks the moment a design has a cycle, which real schemas do have.
 *        MANY_TO_MANY materializes an explicit join table because SQL has no
 *        implicit form of it.
 * WHERE: Registered as the `postgres` target in src/lib/codegen/targets.ts.
 */

import { getDataType } from '@/lib/config/data-types'
import type { CodegenGraph, GeneratedFile, OnDeleteValue } from '@/lib/types'
import { ownerSideOf, pluralize, snakeCase } from './relations'

const SQL_ON_DELETE: Record<OnDeleteValue, string> = {
  cascade: 'CASCADE',
  restrict: 'RESTRICT',
  setNull: 'SET NULL',
}

function tableName(entity: string): string {
  return snakeCase(pluralize(entity))
}

export function generatePostgresDdl(graph: CodegenGraph): GeneratedFile {
  const lines: string[] = [
    '-- Generated by Schema Studio from the design "' + graph.name + '".',
    '-- Review before running against a database.',
    '',
  ]
  const known = new Set(graph.entities.map((entity) => entity.name))

  for (const entity of graph.entities) {
    if (entity.note) lines.push('-- ' + entity.note)
    lines.push('CREATE TABLE ' + tableName(entity.name) + ' (')
    const columns = entity.fields.map((field) => {
      const type = getDataType(field.dataType).postgres
      const parts = ['  ' + snakeCase(field.name), type]
      if (field.isPrimary) parts.push('PRIMARY KEY')
      if (field.isRequired && !field.isPrimary) parts.push('NOT NULL')
      if (field.isUnique && !field.isPrimary) parts.push('UNIQUE')
      if (field.defaultValue) parts.push('DEFAULT ' + field.defaultValue)
      return parts.join(' ')
    })
    lines.push(columns.join(',\n'))
    lines.push(');')
    lines.push('')
  }

  /* Join tables for many-to-many, which has no FK column on either side. */
  const manyToMany = graph.relations.filter(
    (relation) =>
      relation.cardinality === 'MANY_TO_MANY' &&
      known.has(relation.fromEntity) &&
      known.has(relation.toEntity)
  )
  for (const relation of manyToMany) {
    const left = snakeCase(relation.fromEntity)
    const right = snakeCase(relation.toEntity)
    const join = left + '_' + pluralize(right)
    lines.push('-- Join table for ' + relation.fromEntity + ' <-> ' + relation.toEntity)
    lines.push('CREATE TABLE ' + join + ' (')
    lines.push('  ' + left + '_id UUID NOT NULL,')
    lines.push('  ' + right + '_id UUID NOT NULL,')
    lines.push('  PRIMARY KEY (' + left + '_id, ' + right + '_id)')
    lines.push(');')
    lines.push('')
  }

  const constraints: string[] = []
  for (const [index, relation] of graph.relations.entries()) {
    if (!known.has(relation.fromEntity) || !known.has(relation.toEntity)) continue
    const owner = ownerSideOf(relation)
    if (owner === 'none') continue

    const ownerEntity = owner === 'from' ? relation.fromEntity : relation.toEntity
    const targetEntity = owner === 'from' ? relation.toEntity : relation.fromEntity
    const foreignKey = owner === 'from' ? relation.fromField : relation.toField
    const references = owner === 'from' ? relation.toField : relation.fromField
    /* An edge drawn entity-to-entity has no columns to constrain. */
    if (!foreignKey || !references) continue

    constraints.push(
      'ALTER TABLE ' +
        tableName(ownerEntity) +
        '\n  ADD CONSTRAINT fk_' +
        snakeCase(ownerEntity) +
        '_' +
        snakeCase(foreignKey) +
        '_' +
        index +
        '\n  FOREIGN KEY (' +
        snakeCase(foreignKey) +
        ') REFERENCES ' +
        tableName(targetEntity) +
        '(' +
        snakeCase(references) +
        ')\n  ON DELETE ' +
        SQL_ON_DELETE[relation.onDelete] +
        ';'
    )
  }

  if (constraints.length > 0) {
    lines.push('-- Foreign keys')
    lines.push(constraints.join('\n\n'))
    lines.push('')
  }

  if (graph.entities.length === 0) {
    lines.push('-- No entities yet — add some to the canvas.')
  }

  return {
    path: 'schema.sql',
    language: 'sql',
    contents: lines.join('\n'),
  }
}
