/**
 * SOURCE OF TRUTH KEYWORDS: generatePrismaSchema, PRISMA_ON_DELETE
 *
 * WHAT:  Emits a `prisma/schema.prisma` file from a design.
 * WHY:   Field types come from the DATA_TYPES registry rather than a local map,
 *        so adding a data type is still a one-row change in config. Relation
 *        fields come from resolveRelationFields so the owning side and the back
 *        reference cannot disagree — the single most common way a hand-written
 *        generator produces a schema that fails `prisma validate`.
 * WHERE: Registered as the `prisma` target in src/lib/codegen/targets.ts.
 */

import { getDataType } from '@/lib/config/data-types'
import type { CodegenGraph, GeneratedFile, OnDeleteValue } from '@/lib/types'
import { relationFieldName, resolveRelationFields } from './relations'

/* Prisma spells these differently from the diagram's stored values. */
const PRISMA_ON_DELETE: Record<OnDeleteValue, string> = {
  cascade: 'Cascade',
  restrict: 'Restrict',
  setNull: 'SetNull',
}

/* Pads a column so the emitted schema lines up the way `prisma format` would. */
function pad(value: string, width: number): string {
  return value.length >= width ? value : value + ' '.repeat(width - value.length)
}

export function generatePrismaSchema(graph: CodegenGraph): GeneratedFile {
  const relationsByEntity = resolveRelationFields(graph)
  const lines: string[] = [
    '// Generated by Schema Studio from the design "' + graph.name + '".',
    '// Review before running a migration.',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ]

  for (const entity of graph.entities) {
    if (entity.note) lines.push('/// ' + entity.note)
    lines.push('model ' + entity.name + ' {')

    const relationFields = relationsByEntity.get(entity.name) ?? []
    /* Scalar FK columns the owning side must declare. Skipped when the field is
     * already an explicit column on the entity, which is the normal case. */
    const declared = new Set(entity.fields.map((field) => field.name))
    const implicitForeignKeys = relationFields
      .filter((field) => field.owns && field.foreignKey && !declared.has(field.foreignKey))
      .map((field) => field.foreignKey as string)

    const nameWidth = Math.max(
      ...entity.fields.map((field) => field.name.length),
      ...relationFields.map((field) => relationFieldName(field).length),
      ...implicitForeignKeys.map((name) => name.length),
      1
    )

    for (const field of entity.fields) {
      const type = getDataType(field.dataType).prisma
      const optional = field.isRequired || field.isPrimary ? '' : '?'
      const attributes: string[] = []
      if (field.isPrimary) attributes.push('@id')
      if (field.isUnique && !field.isPrimary) attributes.push('@unique')
      if (field.defaultValue) attributes.push('@default(' + field.defaultValue + ')')
      lines.push(
        '  ' +
          pad(field.name, nameWidth) +
          ' ' +
          type +
          optional +
          (attributes.length > 0 ? ' ' + attributes.join(' ') : '')
      )
    }

    /* Foreign keys the design implied but never drew as columns. */
    for (const foreignKey of implicitForeignKeys) {
      lines.push('  ' + pad(foreignKey, nameWidth) + ' String // implied by a relation')
    }

    if (relationFields.length > 0) lines.push('')
    for (const field of relationFields) {
      const property = relationFieldName(field)
      const type = field.isList
        ? field.target + '[]'
        : field.owns
          ? field.target
          : field.target + '?'
      const parts: string[] = []
      if (field.owns && field.foreignKey && field.references) {
        parts.push(
          '@relation("' +
            field.relationName +
            '", fields: [' +
            field.foreignKey +
            '], references: [' +
            field.references +
            '], onDelete: ' +
            PRISMA_ON_DELETE[field.onDelete] +
            ')'
        )
      } else {
        parts.push('@relation("' + field.relationName + '")')
      }
      lines.push('  ' + pad(property, nameWidth) + ' ' + type + ' ' + parts.join(' '))
    }

    lines.push('}')
    lines.push('')
  }

  if (graph.entities.length === 0) {
    lines.push('// No entities yet — add some to the canvas.')
  }

  return {
    path: 'prisma/schema.prisma',
    language: 'prisma',
    contents: lines.join('\n'),
  }
}
